name: 'hello world'
description: 'an example only'
inputs:
  who-to-greet:
    description: 'an input'
    required: true
    default: 'world'
outputs:
  time:
    description: 'the time of the run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
